### ISSUE TITLE
Question on Gate Detection

### ISSUE THREAD

**Issue by juanmed** [SwapUNaph/auto_drone#2]
Hi,

Thanks for sharing your code. I was wondering if you could please expand on several points related to your gate detection and pose estimation algorithm:

1) I see you are using cv2's solvePnP to estimate the pose of the gate in the camera frame. We used the same but got very noisy estimates, with the amplitude of the noise for position estimation noise being around 1m, which rendered it almost useless for going through the gate with only 1m clearance. Did you had any significant noise using solvePnP?

2) Could you please give some insight into what is the logic behing classifying the gates as 'left' or 'right' and the ```gateLeftRightProb``` method? And also maybe into the reason you dropped 'up' and 'down' gate classification? https://github.com/SwapUNaph/auto_drone/blob/b58d6263293796047a1317835a43cf464d5c887d/scripts/gate_detection_and_estimation.py#L498

Thanks!

**Comment by SwapUNaph** [comment]
Hi Juan,
Thanks for taking interest in our autonomous drone racing solution!

1. For gate detection, after thresholding and finding contours, we do polygon approximation to find 4-sided polygons and then filter these polygons based on certain characteristics that resemble those of the gate. viz. aspect ratio, area, solidity and contour region of interest(ROI) mean. This gives us a solid contour that traces the four gate points. And after that the solvePnP is applied to get gate position measurements. 
Now even after doing all that there is noise in the measurements. To remove these, we first pass the measurements through a moving average filter(MVA) of window 5 and then apply Kalman Filter to these filtered values. For Kalman Filter predictions, we integrate the velocity of the drone and then fuse these with gate measurements from MVA filter. 
We got precision in centimeters with the filtering. 

2. Though the code is there for left-right detection we decided not to use it in the competition because it was slowing down the whole system. But still I will go through the logic for that.
The function looks to the left and right of the gate in image and tries to find lines using Hough line transform. These lines are essentially those of the un-lit gate. We then count the number of end points of these lines and score them based on where they should be based on the lit gate.
This score is then normalized to get probabilty i.e. value between 0 and 1.
We found that this method gives very good estimate of which gate is lit and un-lit i.e. left or right but the problem with this solution is it is very slow and hinders the control loop.
Same logic can be applied for vertical gate but we are too close to the gate to get the complete gate in the frame.

Hope this cleared all the doubts.
Regards.

**Comment by juanmed** [comment]
@SwapUNaph Thanks for your clear explanations. Your approach to kalman filtering and left/right/up/down gate classification is quite interesting. In regards of filtering position measurements, we got only until the point of trying to apply low pass filtering to the solvePnP outputs but then went for another method completely different, and did not tried any sort of kalman filter to estimate the position of the gate. It is rather impressive to get centimeter level accuracy with low noise.

In regards to the kalman filter, and if I may ask, what motion model did you assume for the gate? is it simple linear motion? This would imply that you are estimating the position of the gate in the drone-fixed body frame where the gate is in relative motion. I was unable to find the source code for the KalmanFilter class or MVA, was it released? Finally, I see you use a constant process noise of 0.01, is this a value result of some experiments or that was simply choosen and worked?

Thanks again!

**Comment by SwapUNaph** [comment]
@juanmed The model for Kalman filter is simple linear motion: x_dot = v. The matrices for the linear model are there in the code. It is the dynamics of gate position wrt drone in drone's body frame. Initially, we included rotational dynamics as well and made an Extended Kalman Filter, but again it was slow in execution so switched to simpler kalman filter.
The source code for KalmanFilter and MVA filter is in `common_resources.py` script.
The process noise and measurement noise are kind of tuning parameters for the Kalman Filter. These were determined by experimentation.
Regards.

**Comment by juanmed** [comment]
Thanks for the clarification!
